Use new .travis.yml from multi-ghc-travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,138 +1,14 @@
-# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+# This Travis job script has been generated by a script via
+#
+#   make_travis_yml_2.hs '-o' '.travis.yml' '--irc-channel=irc.freenode.org#haskell-lens' 'distributive.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
 language: c
 sudo: false
 
-cache:
-  directories:
-    - $HOME/.cabsnap
-    - $HOME/.cabal/packages
-    - $HOME/.stack
-
-before_cache:
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
-
-matrix:
-  include:
-    - env: CABALVER=1.24 GHCVER=7.0.4 BUILD=cabal
-      compiler: ": #GHC 7.0.4"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.0.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=7.2.2 BUILD=cabal
-      compiler: ": #GHC 7.2.2"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.2.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=7.4.2 BUILD=cabal
-      compiler: ": #GHC 7.4.2"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.4.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=7.6.3 BUILD=cabal
-      compiler: ": #GHC 7.6.3"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.6.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=7.8.4 BUILD=cabal
-      compiler: ": #GHC 7.8.4"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-#    - env: BUILD=stack STACK_YAML=stack-7.8.yaml STACK_OPTIONS=--skip-ghc-check
-#      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-#    - env: BUILD=stack STACK_YAML=stack-7.8.yaml
-#      os: osx
-
-    - env: CABALVER=1.24 GHCVER=7.10.3 BUILD=cabal
-      compiler: ": #GHC 7.10.3"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=8.0.2 BUILD=cabal
-      compiler: ": #GHC 8.0.2"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=2.0 GHCVER=8.2.2 BUILD=cabal
-      compiler: ": #GHC 8.2.2"
-      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-    - env: CABALVER=1.24 GHCVER=head BUILD=cabal CABALFLAGS=--allow-newer
-      compiler: ": #GHC head"
-      addons: {apt: {packages: [cabal-install-1.24,ghc-head,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-#    - env: BUILD=stack STACK_OPTIONS=--skip-ghc-check
-#      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
-
-#    - env: BUILD=stack
-#      os: osx
-
-  allow_failures:
-    - env: CABALVER=1.24 GHCVER=7.0.4 BUILD=cabal
-    - env: CABALVER=1.24 GHCVER=7.2.2 BUILD=cabal
-    - env: CABALVER=1.24 GHCVER=head BUILD=cabal CABALFLAGS=--allow-newer
-
-before_install:
- - unset CC
- - case "$BUILD" in
-     stack)
-       export STACK_VERSION=0.1.3.0;
-       export PATH=~/bin:$PATH;
-       mkdir -p ~/bin;
-       travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/stack-$STACK_VERSION-x86_64-$TRAVIS_OS_NAME.gz | gunzip > ~/bin/stack;
-       chmod a+x ~/bin/stack;
-       scripts/travis_long stack --no-terminal setup;;
-     cabal)
-       export HAPPYVER=1.19.5
-       export ALEXVER=3.1.4
-       export PATH=~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH;;
-   esac
-install:
- - case "$BUILD" in
-     stack)
-       scripts/travis_long stack --no-terminal $STACK_OPTIONS build --only-snapshot -j2;;
-     cabal)
-       echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-       cabal --version;
-       if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-       then
-         zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-              $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-       fi;
-       travis_retry cabal update;
-       cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v $CABALFLAGS> installplan.txt;
-       sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt;
-       if diff -u installplan.txt $HOME/.cabsnap/installplan.txt; then
-         echo "cabal build-cache HIT";
-         rm -rfv .ghc;
-         cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
-         cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
-       else
-         echo "cabal build-cache MISS";
-         rm -rf $HOME/.cabsnap;
-         mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
-         cabal install --only-dependencies --enable-tests --enable-benchmarks $CABALFLAGS;
-       fi;
-       if [ ! -d $HOME/.cabsnap ]; then
-         echo "snapshotting package-db to build-cache";
-         mkdir $HOME/.cabsnap;
-         cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
-         cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
-       fi;;
-   esac
-
-# snapshot package-db on cache miss
-
-# Here starts the actual work to be performed for the package under test;
-# any command which exits with a non-zero exit code causes the build to fail.
-script:
- - case "$BUILD" in
-     stack)
-       scripts/travis_long stack --no-terminal $STACK_OPTIONS build -j2;;
-     cabal)
-       cabal configure --enable-tests -v2 $CABALFLAGS;
-       cabal build;
-       cabal test --show-details=always;
-       cabal bench || true;
-       cabal sdist || true;
-       SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz;
-       if [ -f $SRC_TGZ ]; then (cd dist && cabal install --force-reinstalls "$SRC_TGZ"); fi;
-   esac
+git:
+  submodules: false  # whether to recursively clone submodules
 
 notifications:
   irc:
@@ -140,5 +16,148 @@ notifications:
       - "irc.freenode.org#haskell-lens"
     skip_join: true
     template:
-      - "\x0313distributive\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
+      - "\x0313distributive\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -fv $HOME/.cabal/packages/head.hackage
+
+addons:
+  apt:
+    packages: &apt_packages
+      - ghc-ppa-tools
+      - alex-3.1.4
+      - happy-1.19.5
+
+matrix:
+  include:
+    - compiler: "ghc-7.0.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.0.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.4.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.4.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.6.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.6.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.8.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.8.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.10.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-8.0.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-8.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.4.1"
+      env: GHCHEAD=true
+      addons: {apt: {packages: [*apt_packages,cabal-install-head,ghc-8.4.1], sources: [hvr-ghc]}}
+    - compiler: "ghc-head"
+      env: GHCHEAD=true
+      addons: {apt: {packages: [*apt_packages,cabal-install-head,ghc-head], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - compiler: "ghc-7.0.4"
+    - compiler: "ghc-7.2.2"
+    - compiler: "ghc-8.4.1"
+    - compiler: "ghc-head"
+
+before_install:
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - export HAPPYVER=1.19.5
+  - export ALEXVER=3.1.7
+  - "PATH=~/.cabal/bin:/opt/ghc/bin:/opt/ghc-ppa-tools/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH"
+
+install:
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - INSTALLED=${INSTALLED-true}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project.local
+  - "printf 'packages: \".\"\\n' > cabal.project"
+  # Overlay Hackage Package Index for GHC HEAD: https://github.com/hvr/head.hackage
+  - |
+    if $GHCHEAD; then
+      echo 'allow-newer: *:base, *:template-haskell, *:ghc' >> cabal.project
+      echo 'repository head.hackage' >> cabal.project
+      echo '   url: http://head.hackage.haskell.org/' >> cabal.project
+      echo '   secure: True' >> cabal.project
+      echo '   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740' >> cabal.project
+      echo '              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb' >> cabal.project
+      echo '              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e' >> cabal.project
+      echo '   key-threshold: 3' >> cabal.project
+    fi
+  - cat cabal.project
+  - if $GHCHEAD; then cabal new-update head.hackage -v; fi
+  - if [ -f "./configure.ac" ]; then
+      (cd "."; autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf "."/.ghc.environment.* "."/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+  # test that source-distributions can be generated
+  - (cd "." && cabal sdist)
+  - mv "."/dist/distributive-*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: distributive-*/*.cabal\\n' > cabal.project"
+  # Overlay Hackage Package Index for GHC HEAD: https://github.com/hvr/head.hackage
+  - |
+    if $GHCHEAD; then
+      echo 'allow-newer: *:base, *:template-haskell, *:ghc' >> cabal.project
+      echo 'repository head.hackage' >> cabal.project
+      echo '   url: http://head.hackage.haskell.org/' >> cabal.project
+      echo '   secure: True' >> cabal.project
+      echo '   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740' >> cabal.project
+      echo '              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb' >> cabal.project
+      echo '              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e' >> cabal.project
+      echo '   key-threshold: 3' >> cabal.project
+    fi
+  - cat cabal.project
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # Build with installed constraints for packages in global-db
+  - if $INSTALLED; then echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks $(${HCPKG} list --global --simple-output --names-only | sed 's/\([a-zA-Z0-9-]\{1,\}\) */--constraint="\1 installed" /g') all | sh; else echo "Not building with installed constraints"; fi
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} all; fi
+
+  # haddock
+  - rm -rf ./dist-newstyle
+  - if $HADDOCK; then cabal new-haddock -w ${HC} --disable-tests --disable-benchmarks all; else echo "Skipping haddock generation";fi
+
+# REGENDATA ["-o",".travis.yml","--irc-channel=irc.freenode.org#haskell-lens","distributive.cabal"]
 # EOF
